#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppodealXamarinSample.Resource", IsApplication=true)]

namespace AppodealXamarinSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int advertisement = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int loading_animation = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int adSize = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int adSizes = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int adUnitId = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int browser_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int browser_close = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int browser_left_arrow = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int browser_refresh = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int browser_right_arrow = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int browser_unleft_arrow = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int browser_unright_arrow = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_ad_bg = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btnstyle = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int cmasdk_market_top_gp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ico_banner_mid_cm = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ico_cm = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int img_interstitial_ads_cm_icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int img_interstitial_ads_icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int img_interstitial_adsby_bg = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int img_interstitial_close_icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int interstital_ad_body_bg = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int progressbar = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int vast_close = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int vast_install = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int vast_progress_style = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int vast_shrink = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int vast_stranch = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int vast_volume_off = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int vast_volume_on = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int vast_watchagain = 2130837530;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int adjust_height = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int adjust_width = 2131230721;
			
			// aapt resource value: 0x7f080031
			public const int appodealBannerView = 2131230769;
			
			// aapt resource value: 0x7f080005
			public const int browser_back = 2131230725;
			
			// aapt resource value: 0x7f080008
			public const int browser_close = 2131230728;
			
			// aapt resource value: 0x7f080006
			public const int browser_forward = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int browser_refresh = 2131230727;
			
			// aapt resource value: 0x7f08001a
			public const int btn_calltoaction = 2131230746;
			
			// aapt resource value: 0x7f080036
			public const int cm_icon = 2131230774;
			
			// aapt resource value: 0x7f080025
			public const int cover_top = 2131230757;
			
			// aapt resource value: 0x7f080038
			public const int framelayout = 2131230776;
			
			// aapt resource value: 0x7f08000c
			public const int full_screen_video = 2131230732;
			
			// aapt resource value: 0x7f080030
			public const int hideB = 2131230768;
			
			// aapt resource value: 0x7f080033
			public const int img_icon = 2131230771;
			
			// aapt resource value: 0x7f080035
			public const int img_mainbackground = 2131230773;
			
			// aapt resource value: 0x7f08002d
			public const int initialize = 2131230765;
			
			// aapt resource value: 0x7f080013
			public const int iv_close = 2131230739;
			
			// aapt resource value: 0x7f080018
			public const int iv_coverimage = 2131230744;
			
			// aapt resource value: 0x7f080016
			public const int iv_icon = 2131230742;
			
			// aapt resource value: 0x7f08001e
			public const int jump_to_main = 2131230750;
			
			// aapt resource value: 0x7f080012
			public const int ll_ad_body = 2131230738;
			
			// aapt resource value: 0x7f080014
			public const int ll_ad_detail = 2131230740;
			
			// aapt resource value: 0x7f080032
			public const int ll_parentGroup = 2131230770;
			
			// aapt resource value: 0x7f080003
			public const int main_rl = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int none = 2131230722;
			
			// aapt resource value: 0x7f08001c
			public const int number = 2131230748;
			
			// aapt resource value: 0x7f080004
			public const int panel_ll = 2131230724;
			
			// aapt resource value: 0x7f08001f
			public const int rl_contentview = 2131230751;
			
			// aapt resource value: 0x7f08001b
			public const int rl_time_layout = 2131230747;
			
			// aapt resource value: 0x7f080011
			public const int root_view = 2131230737;
			
			// aapt resource value: 0x7f08002f
			public const int showB = 2131230767;
			
			// aapt resource value: 0x7f08002e
			public const int showI = 2131230766;
			
			// aapt resource value: 0x7f080015
			public const int tv_ad_detail = 2131230741;
			
			// aapt resource value: 0x7f080037
			public const int tv_btn = 2131230775;
			
			// aapt resource value: 0x7f08002b
			public const int tv_cancel = 2131230763;
			
			// aapt resource value: 0x7f080019
			public const int tv_des = 2131230745;
			
			// aapt resource value: 0x7f080034
			public const int tv_description = 2131230772;
			
			// aapt resource value: 0x7f08002c
			public const int tv_download = 2131230764;
			
			// aapt resource value: 0x7f080017
			public const int tv_title = 2131230743;
			
			// aapt resource value: 0x7f080021
			public const int vast_ad = 2131230753;
			
			// aapt resource value: 0x7f080028
			public const int vast_detail = 2131230760;
			
			// aapt resource value: 0x7f08000f
			public const int vast_full_img_stranch = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int vast_full_img_volume = 2131230736;
			
			// aapt resource value: 0x7f080022
			public const int vast_img_stranch = 2131230754;
			
			// aapt resource value: 0x7f080023
			public const int vast_img_volume = 2131230755;
			
			// aapt resource value: 0x7f080027
			public const int vast_install = 2131230759;
			
			// aapt resource value: 0x7f080024
			public const int vast_progress = 2131230756;
			
			// aapt resource value: 0x7f080020
			public const int vast_rl = 2131230752;
			
			// aapt resource value: 0x7f080029
			public const int vast_small_ad = 2131230761;
			
			// aapt resource value: 0x7f08002a
			public const int vast_small_view_close = 2131230762;
			
			// aapt resource value: 0x7f080026
			public const int vast_watch_again = 2131230758;
			
			// aapt resource value: 0x7f08001d
			public const int vertical_line = 2131230749;
			
			// aapt resource value: 0x7f08000e
			public const int video_full_screen = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int video_full_screen_progress = 2131230733;
			
			// aapt resource value: 0x7f08000b
			public const int wait_progressbar = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int webview = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int webview_rl = 2131230729;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_picks_browser = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_picks_loading = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int cm_activity_full_screen_video = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int cm_activity_picks_interstitial = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int cm_splash_time = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int cm_vast_ad_layout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int cm_vast_small_view = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int gps_dialog = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int origin_picks_banner_mid = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int origin_picks_banner_smail = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050005
			public const int accept = 2131034117;
			
			// aapt resource value: 0x7f05000e
			public const int app_name = 2131034126;
			
			// aapt resource value: 0x7f050001
			public const int auth_google_play_services_client_facebook_display_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int auth_google_play_services_client_google_display_name = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int cancel = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_unknown_issue = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int create_calendar_message = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int create_calendar_title = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int decline = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int download = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int downloading = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int gps_prompt_context = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int gps_prompt_title = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int hello = 2131034127;
			
			// aapt resource value: 0x7f050004
			public const int store_picture_message = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int store_picture_title = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_IAPTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int cm_interstital = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
