#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppodealXamarinSample.Resource", IsApplication=true)]

namespace AppodealXamarinSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f090000
			public const int adtypes_array = 2131296256;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int adSize = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int adSizes = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int adUnitId = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010006
			public const int layoutManager = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int reverseLayout = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int spanCount = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int stackFromEnd = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int item_touch_helper_swipe_escape_max_velocity = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int item_touch_helper_swipe_escape_velocity = 2131165186;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080004
			public const int adType = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int adjust_height = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int adjust_width = 2131230722;
			
			// aapt resource value: 0x7f080017
			public const int appodealBannerView = 2131230743;
			
			// aapt resource value: 0x7f08000e
			public const int autocache = 2131230734;
			
			// aapt resource value: 0x7f080006
			public const int cache = 2131230726;
			
			// aapt resource value: 0x7f080011
			public const int disable_728x90_banners = 2131230737;
			
			// aapt resource value: 0x7f080010
			public const int disable_banner_animation = 2131230736;
			
			// aapt resource value: 0x7f080013
			public const int disable_location_permission_check = 2131230739;
			
			// aapt resource value: 0x7f08000f
			public const int disable_smart_banners = 2131230735;
			
			// aapt resource value: 0x7f080014
			public const int disable_write_external_storage_check = 2131230740;
			
			// aapt resource value: 0x7f080012
			public const int enable_trigger_on_loaded_on_precache = 2131230738;
			
			// aapt resource value: 0x7f08000b
			public const int hide = 2131230731;
			
			// aapt resource value: 0x7f080005
			public const int initialize = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int is_loaded = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int is_precache = 2131230728;
			
			// aapt resource value: 0x7f080000
			public const int item_touch_helper_previous_elevation = 2131230720;
			
			// aapt resource value: 0x7f08000c
			public const int logging = 2131230732;
			
			// aapt resource value: 0x7f080015
			public const int native_ad_holder = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int native_ad_view_app_wall = 2131230742;
			
			// aapt resource value: 0x7f080003
			public const int none = 2131230723;
			
			// aapt resource value: 0x7f080009
			public const int show = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int show_with_placement = 2131230730;
			
			// aapt resource value: 0x7f08000d
			public const int testing = 2131230733;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040005
			public const int accept = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public const int app_name = 2130968586;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_unknown_issue = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int create_calendar_message = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int create_calendar_title = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int decline = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int hello = 2130968585;
			
			// aapt resource value: 0x7f040004
			public const int store_picture_message = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int store_picture_title = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_IAPTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
